[package]
name = "juniper_lean_to_rewrite"
version = "0.1.0"
edition = "2021"

[dependencies]
lean_parse = { path = "../lean_parse" }
juniper_math_expression = { path = "../juniper_math_expression" }
egg = "0.9.5"
anyhow = "1.0.94"
