[package]
name = "lean_parse"
version = "0.1.0"
edition = "2021"

[dependencies]
display_tree = "1.1.2"
num = { version = "0.4.3", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
